FROM python:3.9-slim

# Install Java (Required for PySpark)
RUN apt-get update && \
    apt-get install -y default-jre procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the pre-downloaded PySpark file and install it first
COPY pyspark-3.5.0.tar.gz .
RUN pip install pyspark-3.5.0.tar.gz && rm pyspark-3.5.0.tar.gz

# Now copy requirements and install the rest
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir deltalake==0.15.0 psycopg2-binary==2.9.9

CMD ["python"]
